name: analysis-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - h5py=3.9.0
  - hdf5=1.12.1
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran5=11.2.0
  - libnghttp2=1.57.0
  - libssh2=1.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
