name: analysis-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - h5py=3.9.0
  - hdf5=1.12.1
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran5=11.2.0
  - libnghttp2=1.57.0
  - libssh2=1.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - 0-0-1==0.0.1
    - absl-py==2.1.0
    - asteval==0.9.32
    - astunparse==1.6.3
    - build==1.2.1
    - cachetools==5.3.3
    - cfgv==3.4.0
    - contourpy==1.1.1
    - corrfitter==8.2
    - distlib==0.3.8
    - filelock==3.13.3
    - flatbuffers==24.3.25
    - fonttools==4.51.0
    - gast==0.4.0
    - google-auth==2.29.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.62.2
    - gvar==13.0.2
    - identify==2.5.35
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - julia==0.6.2
    - keras==2.13.1
    - libclang==18.1.1
    - lmfit==1.2.2
    - lsdensities==0.0.1
    - lsqfit==13.2
    - markdown==3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - nh3==0.2.17
    - nodeenv==1.8.0
    - numpy==1.22.4
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pep517==0.13.1
    - pkginfo==1.10.0
    - platformdirs==4.2.0
    - pre-commit==3.5.0
    - progressbar==2.5
    - protobuf==4.25.3
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pygments==2.17.2
    - pyproject-hooks==1.1.0
    - readme-renderer==43.0
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==13.7.1
    - rsa==4.9
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.4.0
    - tomli==2.0.1
    - twine==5.0.0
    - typing-extensions==4.5.0
    - uncertainties==3.1.7
    - vegas==6.1
    - virtualenv==20.25.1
