name: spectral-density-202407
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - arpack=3.9.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - curl=8.8.0
  - dav1d=1.2.1
  - expat=2.6.2
  - ffmpeg=7.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - git=2.45.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=9.0.0
  - icu=73.2
  - julia=1.10.4
  - keyutils=1.6.1
  - lame=3.100
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgit2=1.8.1
  - libglib=2.80.2
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libopenblas-ilp64=0.3.27
  - libopenlibm4=0.8.1
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - mbedtls=3.5.1
  - metis=5.1.0
  - mpfr=4.2.1
  - ncurses=6.5
  - nettle=3.9.1
  - ocl-icd=2.3.2
  - openblas-ilp64=0.3.27
  - openh264=2.4.1
  - openlibm=0.8.1
  - openssl=3.3.1
  - p11-kit=0.24.1
  - p7zip=16.02
  - pcre2=10.44
  - perl=5.32.1
  - pip=24.0
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pugixml=1.14
  - python=3.12.4
  - readline=8.2
  - setuptools=70.1.1
  - snappy=1.2.1
  - suitesparse=7.7.0
  - svt-av1=2.1.2
  - tbb=2021.12.0
  - tk=8.6.13
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - asteval==0.9.33
      - contourpy==1.2.1
      - corrfitter==8.2
      - cycler==0.12.1
      - dill==0.3.8
      - fonttools==4.53.0
      - gvar==13.1
      - h5py==3.11.0
      - kiwisolver==1.4.5
      - lmfit==1.3.1
      - lsdensities==0.0.1
      - lsqfit==13.2.2
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.3.0
      - progressbar==2.5
      - pyparsing==3.1.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.14.0
      - six==1.16.0
      - tzdata==2024.1
      - uncertainties==3.2.1
      - vegas==6.1.2
